### ISSUE TITLE
Förstår inte varifrån session kommer

### ISSUE THREAD

**Issue by quaspar** [quaspar/despairbnb#1]
rad 175 i schema.js ser ut så här:

      resolve: (session) => getUser(session.userId),

Varifrån kommer session-variabeln? Jag fattar inte.

Jag har gjort om App-komponenten och AppHomeRoute så att de återspeglar vårt schema. Jag får inga varningar nu, men heller inget innehåll på sidan ...

**Comment by remipou** [comment]
https://github.com/quaspar/despairbnb/commit/8ee24271937b766d6ad1c757a093fd47163de031
